using Geotab.Checkmate.ObjectModel;
using MyGeotabAPIAdapter.Database;
using MyGeotabAPIAdapter.Database.Models;
using MyGeotabAPIAdapter.Helpers;
using MyGeotabAPIAdapter.MyGeotabAPI;

namespace MyGeotabAPIAdapter.GeotabObjectMappers
{
    /// <summary>
    /// Interface for a class with methods involving mapping between <see cref="ZoneType"/> and <see cref="DbZoneType2"/> entities.
    /// </summary>
    public class GeotabZoneTypeDbZoneType2ObjectMapper : IGeotabZoneTypeDbZoneType2ObjectMapper
    {
        readonly IDateTimeHelper dateTimeHelper;
        readonly IStringHelper stringHelper;

        public GeotabZoneTypeDbZoneType2ObjectMapper(IDateTimeHelper dateTimeHelper, IStringHelper stringHelper)
        { 
            this.dateTimeHelper = dateTimeHelper;         
			this.stringHelper = stringHelper;
        }

        /// <inheritdoc/>
        public DbZoneType2 CreateEntity(ZoneType entityToMapTo, Common.DatabaseRecordStatus entityStatus = Common.DatabaseRecordStatus.Active)
        {
            DbZoneType2 dbZoneType2 = new()
            {
                DatabaseWriteOperationType = Common.DatabaseWriteOperationType.Insert,
                EntityStatus = (int)entityStatus,
                GeotabId = entityToMapTo.Id.ToString(),
                Name = entityToMapTo.Name,
                RecordLastChangedUtc = DateTime.UtcNow
            };
            if (entityToMapTo.Comment != null && entityToMapTo.Comment.Length > 0)
            {
                dbZoneType2.Comment = entityToMapTo.Comment;
            }
            return dbZoneType2;
        }

        /// <inheritdoc/>
        public bool EntityRequiresUpdate(DbZoneType2 entityToEvaluate, ZoneType entityToMapTo)
        {
            if (entityToEvaluate.GeotabId != entityToMapTo.Id.ToString())
            {
                throw new ArgumentException($"Cannot compare {nameof(DbZoneType2)} '{entityToEvaluate.id}' with {nameof(ZoneType)} '{entityToMapTo.Id}' because the IDs do not match.");
            }

            if (stringHelper.AreEqual(entityToEvaluate.Comment, entityToMapTo.Comment) == false)
            {
                return true;
            }
            if (stringHelper.AreEqual(entityToEvaluate.Name, entityToMapTo.Name) == false)
            {
                return true;
            }
            return false;
        }

        /// <inheritdoc/>
        public DbZoneType2 UpdateEntity(DbZoneType2 entityToUpdate, ZoneType entityToMapTo, Common.DatabaseRecordStatus entityStatus = Common.DatabaseRecordStatus.Active)
        {
            if (entityToUpdate.GeotabId != entityToMapTo.Id.ToString())
            {
                throw new ArgumentException($"Cannot update {nameof(DbZoneType2)} '{entityToUpdate.id} (GeotabId {entityToUpdate.GeotabId})' with {nameof(ZoneType)} '{entityToMapTo.Id}' because the GeotabIds do not match.");
            }

            var updatedDbZoneType2 = CreateEntity(entityToMapTo);

            // Update id since id is auto-generated by the database on insert and is therefor not set by the CreateEntity method.
            updatedDbZoneType2.id = entityToUpdate.id;
            updatedDbZoneType2.DatabaseWriteOperationType = Common.DatabaseWriteOperationType.Update;

            return updatedDbZoneType2;
        }
    }
}
