name: Build and Deploy My Geotab API Adapter On Merge

concurrency:
  group: mygeotab-api-adapter-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

# This tells github when we want our pipeline to be triggered.
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-and-deploy-mygeotab-api-adapter.yml"
      - "MyGeotabAPIAdapter**"
      - "!DeployToAzure"
      - "!**/catalog-info.yaml"
  pull_request:
    branches:
      - main
    paths:
    - ".github/workflows/build-and-deploy-mygeotab-api-adapter.yml"
    - "MyGeotabAPIAdapter**"
    - "!DeployToAzure"
    - "!**/catalog-info.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up authentication and manifest state ready to start building and pushing containers
      - name: initialise for build
        uses: eroad/github-actions-pipelines/actions/dist/init-build-aws@v5.0
        with:
            product_domain: core
            system_name: mygeotab-api-adapter
      - name: build image
        uses: eroad/github-actions-pipelines/actions/dist/docker-build@v5.0
        with:
          image_name: mygeotab-api-adapter
          dockerfile: ./config/docker/MyGeotabAPIAdapter.dockerfile
          includes: **
          context: .
      - name: post build
        if: ${{ endsWith(github.ref, '/main') }}
        uses: eroad/github-actions-pipelines/actions/dist/post-build@v5.0
